services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data

  # system: PostgreSql
  # server: postgres
  # username: postgres
  # password: 123456
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - 8080:8080
