services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
