services:
  # large-file-upload:
  #   container_name: large-file-upload
  #   build:
  #     context: .
  #     dockerfile: ./apps/large-file-upload/Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000

  stackoverflow:
    container_name: stackoverflow
    build:
      context: .
      dockerfile: ./apps/stackoverflow/Dockerfile
      args:
        - POSTGRES_PRISMA_URL=postgres://postgres:123456@127.0.0.1:5432/stackoverflow
        - POSTGRES_URL_NON_POOLING=postgres://postgres:123456@127.0.0.1:5432/stackoverflow
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_c3RpcnJlZC1mbGVhLTMuY2xlcmsuYWNjb3VudHMuZGV2JA
        - CLERK_SECRET_KEY=sk_test_Xx0zLQaur636egnWNgSPADqUxgT6U9vzno2DZ8W6g1
    restart: always
    ports:
      - 3000:3001
    networks:
      - stack-network

networks:
  stack-network:
    external: true
