services:
  stackoverflow-postgres:
    container_name: stackoverflow-postgres
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    networks:
      - stack-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - stack-network

networks:
  stack-network:
    driver: bridge
