services:
  stackoverflow:
    container_name: stackoverflow
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - POSTGRES_PRISMA_URL=postgres://postgres:123456@127.0.0.1:5432/stackoverflow
        - POSTGRES_URL_NON_POOLING=postgres://postgres:123456@127.0.0.1:5432/stackoverflow
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_c3RpcnJlZC1mbGVhLTMuY2xlcmsuYWNjb3VudHMuZGV2JA
        - CLERK_SECRET_KEY=sk_test_Xx0zLQaur636egnWNgSPADqUxgT6U9vzno2DZ8W6g1
      network: host
    restart: always

  stackoverflow-postgres:
    container_name: stackoverflow-postgres
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    network_mode: host

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    network_mode: host
