name: "nextjs-practical-cases"

services:
  stackoverflow:
    container_name: stackoverflow-next.js
    build:
      context: ../../../
      dockerfile: ./apps/stackoverflow/deploy/Dockerfile
      args:
        - POSTGRES_PRISMA_URL=postgres://postgres:${POSTGRES_PASSWORD}@127.0.0.1:5432/stackoverflow
        - POSTGRES_URL_NON_POOLING=postgres://postgres:${POSTGRES_PASSWORD}@127.0.0.1:5432/stackoverflow
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
        - TURBO_TEAM=${TURBO_TEAM}
        - TURBO_TOKEN=${TURBO_TOKEN}
        - APP_DIR=apps/stackoverflow
        - APP_PACKAGE_NAME=@npc/stackoverflow
      network: host
    restart: always
    environment:
      - POSTGRES_PRISMA_URL=postgres://postgres:${POSTGRES_PASSWORD}@stackoverflow-postgres:5432/stackoverflow
      - POSTGRES_URL_NON_POOLING=postgres://postgres:${POSTGRES_PASSWORD}@stackoverflow-postgres:5432/stackoverflow
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    ports:
      - 3001:3000
    networks:
      - stackoverflow-network

networks:
  stackoverflow-network:
    driver: bridge
    external: true
