name: "nextjs-practical-cases"

services:
  template:
    container_name: template
    build:
      context: ../../../
      dockerfile: ./apps/template/deploy/Dockerfile
      args:
        - TURBO_TEAM=${TURBO_TEAM}
        - TURBO_TOKEN=${TURBO_TOKEN}
        - APP_DIR=apps/template
        - APP_PACKAGE_NAME=@npc/template
    restart: always
    ports:
      - 3000:3000
