services:
  stackoverflow:
    container_name: stackoverflow-next.js
    build:
      context: ../../
      dockerfile: ./apps/stackoverflow/Dockerfile
      args:
        - POSTGRES_PRISMA_URL=postgres://postgres:123456@127.0.0.1:5432/stackoverflow
        - POSTGRES_URL_NON_POOLING=postgres://postgres:123456@127.0.0.1:5432/stackoverflow
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_c3RpcnJlZC1mbGVhLTMuY2xlcmsuYWNjb3VudHMuZGV2JA
        - CLERK_SECRET_KEY=sk_test_Xx0zLQaur636egnWNgSPADqUxgT6U9vzno2DZ8W6g1
        - TURBO_TEAM=xiaosen7s-projects
        - TURBO_TOKEN=P23UhrF9MQkVfKs6ClUS0bx8
      network: host
    restart: always
    environment:
      - POSTGRES_PRISMA_URL=postgres://postgres:123456@stackoverflow-postgres:5432/stackoverflow
      - POSTGRES_URL_NON_POOLING=postgres://postgres:123456@stackoverflow-postgres:5432/stackoverflow
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_c3RpcnJlZC1mbGVhLTMuY2xlcmsuYWNjb3VudHMuZGV2JA
      - CLERK_SECRET_KEY=sk_test_Xx0zLQaur636egnWNgSPADqUxgT6U9vzno2DZ8W6g1
    ports:
      - 3001:3000
    networks:
      - stackoverflow-network

networks:
  stackoverflow-network:
    driver: bridge
    external: true
