services:
  stackoverflow:
    container_name: stackoverflow
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - POSTGRES_PRISMA_URL=postgres://postgres:123456@stackoverflow-network:5432/stackoverflow
        - POSTGRES_URL_NON_POOLING=postgres://postgres:123456@stackoverflow-network:5432/stackoverflow
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_c3RpcnJlZC1mbGVhLTMuY2xlcmsuYWNjb3VudHMuZGV2JA
        - CLERK_SECRET_KEY=sk_test_Xx0zLQaur636egnWNgSPADqUxgT6U9vzno2DZ8W6g1
      network: stackoverflow-network
    restart: always

networks:
  stackoverflow-network:
