services:
  stackoverflow-postgres:
    container_name: stackoverflow-postgres
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 123456
    networks:
      - stackoverflow-network

  stackoverflow-adminer:
    container_name: stackoverflow-adminer
    image: adminer
    restart: always
    networks:
      - stackoverflow-network
    ports:
      - 8080:8080

networks:
  stackoverflow-network:
