# .github/actions/docker-build/action.yml
name: "Docker Build and Push"
description: "Build and push Docker images for different branches"

inputs:
  APP_DIR:
    description: "Application directory"
    required: true
  APP_PACKAGE_NAME:
    description: "Application package name"
    required: true
  IMAGE_NAME:
    description: "Docker image name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login Registry
      if: github.ref == 'refs/heads/main'
      run: |
        echo ${{ secrets.PAT }} | docker login ${{ secrets.REGISTRY }} -u ${{ github.actor }} --password-stdin

    - name: Build Docker Image
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        push: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
        tags: ${{ inputs.IMAGE_NAME }}
        cache-from: type=registry,ref=${{ inputs.IMAGE_NAME }}
        cache-to: type=inline
        context: .
        file: ${{ secrets.DOCKERFILE }}
        build-args: |
          TURBO_TEAM=${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
          APP_DIR=${{ inputs.APP_DIR }}
          APP_PACKAGE_NAME=${{ inputs.APP_PACKAGE_NAME }}

    - run: |
        echo "Docker Image ID: ${{ steps.docker_build.outputs.imageid }}"
        echo "Docker Image digest: ${{ steps.docker_build.outputs.digest }}"
        echo "Docker Image metadata: ${{ steps.docker_build.outputs.metadata }}"
