name: Deploy next.js-practical-cases

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - run: corepack enable pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo lint check-types

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - run: corepack enable pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo test

  deploy:
    name: Deploy Image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
            export CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
            export TURBO_TEAM=${{ secrets.TURBO_TEAM }}
            export TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}

            cd ${{ secrets.VPS_WORK_DIR }} 
            git pull --rebase
            bash ./deploy.sh
            exit
