name: Deploy next.js-practical-cases

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.actor }}/large-file-upload:latest
  DOCKERFILE: ./deploy/Dockerfile
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
  CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  deploy:
    name: Deploy Image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.VPS_WORK_DIR }} 
            echo $IMAGE_NAME
            git pull --rebase
            bash ./deploy.sh
            exit
