name: Deploy next.js-practical-cases

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy large-file-upload
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
            export CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
            export TURBO_TEAM=${{ secrets.TURBO_TEAM }}
            export TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}

            cd ${{ secrets.VPS_WORK_DIR }} 
            git pull --rebase
            bash ./apps/large-file-upload/deploy/deploy.sh
            exit
      - name: Deploy stackoverflow
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
            export CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
            export TURBO_TEAM=${{ secrets.TURBO_TEAM }}
            export TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}

            cd ${{ secrets.VPS_WORK_DIR }} 
            git pull --rebase
            bash ./apps/stackoverflow/deploy/deploy.sh
            exit
