# app-template-ci.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Call Docker Build Action
        uses: ./.github/actions/docker-build
        with:
          APP_DIR: apps/template
          APP_PACKAGE_NAME: "@npcs/template"
          IMAGE_NAME: ghcr.io/${{ github.actor }}/npcs-template:latest
