# app-template-ci.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Call Docker Build Action
        uses: ./.github/actions/docker-build
        with:
          APP_DIR: apps/template
          APP_PACKAGE_NAME: "@npcs/template"
          IMAGE_NAME: ghcr.io/${{ github.actor }}/npcs-template:latest
          PAT: ${{ secrets.PAT }}
          REGISTRY: ghcr.io
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          DOCKERFILE: ${{ secrets.DOCKERFILE }}
