# app-template-ci.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Call Docker Build Action
        uses: ./.github/actions/docker-build@v1
        with:
          REGISTRY: ghcr.io
          PAT: ${{ secrets.PAT }}
          APP_DIR: apps/template
          APP_PACKAGE_NAME: "@npcs/template"
          DOCKERFILE: ./Dockerfile
          IMAGE_NAME: ghcr.io/${{ github.actor }}/npcs-template:latest
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
